#!/usr/bin/env python3
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import csv
import re
import subprocess
from collections import Counter
from pathlib import Path


SPDX_RE = re.compile(
    r"(?m)^[ \t]*(?:(?:#|//|/\*|\*|<!--|;|--)[ \t]*)?"
    r"SPDX-License-Identifier:\s*([^\n\r*<]+)"
)
COPYRIGHT_RE = re.compile(r"(?i)\bcopyright\b[^\n\r]*")
GENERATED_RE = re.compile(
    r"(?i)\b(auto[- ]?generated|generated by|do not edit|machine generated)\b"
)

INVENTORY_OUTPUTS = {
    "docs/relicensing/inventory.md",
    "docs/relicensing/inventory.tsv",
}

VENDORED_PREFIXES = (
    "abseil/",
    "licenses/",
    "seastar/",
    "swagger-ui/",
)

GENERATED_PREFIXES = (
    "api/api-doc/",
    "api/api-docs/",
)


def repo_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    return Path(result.stdout.strip())


def tracked_files(root: Path) -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        check=True,
        stdout=subprocess.PIPE,
    )
    paths = []
    for raw_path in result.stdout.split(b"\0"):
        if not raw_path:
            continue
        rel = raw_path.decode()
        if rel in INVENTORY_OUTPUTS:
            continue
        paths.append(root / rel)
    return paths


def decode_sample(path: Path) -> tuple[str, bool]:
    if path.is_dir():
        return "", False
    data = path.read_bytes()
    is_binary = b"\0" in data[:8192]
    if is_binary:
        data = data[:8192]
    return data.decode("utf-8", errors="replace"), is_binary


def clean_spdx(value: str) -> str:
    value = value.strip()
    value = value.removesuffix("*/").strip()
    return value.strip(" #;")


def classify_license(spdx_values: list[str]) -> str:
    if not spdx_values:
        return "unknown-license"

    joined = " ".join(spdx_values)
    has_agpl = "AGPL" in joined
    has_apache = "Apache-2.0" in joined
    has_operator = any(op in joined for op in (" OR ", " AND ", " WITH ", "(", ")"))

    if has_agpl and has_apache:
        return "dual-licensed"
    if has_agpl:
        return "AGPL-only"
    if has_apache and not has_operator:
        return "Apache-only"
    if has_apache:
        return "Apache-plus"
    return "other-license"


def path_flags(rel: str, text: str) -> list[str]:
    flags: list[str] = []
    if rel in {prefix.rstrip("/") for prefix in VENDORED_PREFIXES} or rel.startswith(
        VENDORED_PREFIXES
    ):
        flags.append("vendored")
    generated_marker = any(
        GENERATED_RE.search(line)
        and "GENERATED_RE" not in line
        and "auto[- ]?generated" not in line
        for line in text.splitlines()
    )
    if rel.startswith(GENERATED_PREFIXES) or generated_marker:
        flags.append("generated")
    return flags


def inventory_rows(root: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in tracked_files(root):
        rel = path.relative_to(root).as_posix()
        text, is_binary = decode_sample(path)
        spdx_values = sorted({clean_spdx(m.group(1)) for m in SPDX_RE.finditer(text)})
        copyrights = sorted(
            {
                match.group(0).strip()
                for line in text.splitlines()
                if "COPYRIGHT_RE" not in line and '"copyright"' not in line
                for match in COPYRIGHT_RE.finditer(line)
            }
        )
        flags = path_flags(rel, text)
        if path.is_dir():
            flags.append("gitlink")
        rows.append(
            {
                "path": rel,
                "license_class": classify_license(spdx_values),
                "spdx": "; ".join(spdx_values) if spdx_values else "",
                "copyright": " | ".join(copyrights),
                "flags": "; ".join(flags),
                "binary": "yes" if is_binary else "no",
            }
        )
    return rows


def write_tsv(path: Path, rows: list[dict[str, str]]) -> None:
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=["path", "license_class", "spdx", "copyright", "flags", "binary"],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def markdown_table(counter: Counter[str]) -> str:
    lines = ["| Category | Files |", "|---|---:|"]
    for key, count in sorted(counter.items()):
        lines.append(f"| {key} | {count} |")
    return "\n".join(lines)


def write_markdown(path: Path, rows: list[dict[str, str]], tsv_name: str) -> None:
    license_counts = Counter(row["license_class"] for row in rows)
    flag_counts: Counter[str] = Counter()
    for row in rows:
        for flag in filter(None, row["flags"].split("; ")):
            flag_counts[flag] += 1

    unknown_examples = [
        row["path"] for row in rows if row["license_class"] == "unknown-license"
    ][:25]
    generated_examples = [row["path"] for row in rows if "generated" in row["flags"]][:25]
    vendored_examples = [row["path"] for row in rows if "vendored" in row["flags"]][:25]

    def bullet_list(values: list[str]) -> str:
        if not values:
            return "- none"
        return "\n".join(f"- `{value}`" for value in values)

    path.write_text(
        "\n".join(
            [
                "# License Inventory",
                "",
                "This inventory is generated from tracked files in the repository.",
                "It is an audit starting point, not a legal conclusion.",
                "",
                "- Source: tracked files in the current working tree",
                f"- Generator: `docs/relicensing/generate-inventory.py`",
                f"- Complete per-file inventory: `{tsv_name}`",
                f"- Tracked files scanned: `{len(rows)}`",
                "",
                "## License Classes",
                "",
                markdown_table(license_counts),
                "",
                "## File Flags",
                "",
                markdown_table(flag_counts),
                "",
                "## Classification Rules",
                "",
                "- `AGPL-only`: SPDX expression references AGPL and not Apache-2.0.",
                "- `Apache-only`: SPDX expression is Apache-2.0 without compound operators.",
                "- `dual-licensed`: SPDX expression references both AGPL and Apache-2.0.",
                "- `Apache-plus`: SPDX expression references Apache-2.0 with additional operators.",
                "- `other-license`: SPDX expression exists but is not AGPL or Apache-2.0.",
                "- `unknown-license`: no SPDX identifier was found in the scanned file.",
                "- `generated`: path or file contents indicate generated output.",
                "- `vendored`: path is under a known third-party/vendor directory.",
                "- `gitlink`: tracked path is a submodule/gitlink entry.",
                "",
                "## Unknown-License Examples",
                "",
                bullet_list(unknown_examples),
                "",
                "## Generated Examples",
                "",
                bullet_list(generated_examples),
                "",
                "## Vendored Examples",
                "",
                bullet_list(vendored_examples),
                "",
                "## Next Audit Steps",
                "",
                "- Review `unknown-license` files and add SPDX headers where appropriate.",
                "- Confirm whether generated files inherit license from their generator or input.",
                "- Confirm vendored license obligations against upstream license files.",
                "- Keep this inventory updated when files are added, removed, or relicensed.",
                "",
            ]
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="docs/relicensing")
    args = parser.parse_args()

    root = repo_root()
    output_dir = root / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = inventory_rows(root)
    write_tsv(output_dir / "inventory.tsv", rows)
    write_markdown(output_dir / "inventory.md", rows, "inventory.tsv")


if __name__ == "__main__":
    main()
