name: clang-nightly

on:
  schedule:
    # only at 5AM Saturday
    - cron: '0 5 * * SAT'
  workflow_dispatch:

env:
  # use the development branch explicitly
  CLANG_VERSION: 20
  BUILD_DIR: build

permissions: {}

# cancel the in-progress run upon a repush
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-dev:
    name: Build with clang nightly
    runs-on: depot-ubuntu-24.04-8
    container: fedora:40
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 2G
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_NOHASHDIR: true
    strategy:
      matrix:
        build_type:
          - Debug
          - RelWithDebInfo
          - Dev
    steps:
      - run: |
          sudo dnf -y install git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build dependencies
        run: |
          # use the copr repo for llvm snapshot builds, see
          # https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots/
          sudo dnf -y install 'dnf-command(copr)'
          sudo dnf copr enable -y @fedora-llvm-team/llvm-snapshots
          # do not install java dependencies, which is not only not used here
          sed -i.orig \
            -e '/tools\/.*\/install-dependencies.sh/d' \
            -e 's/(minio_download_jobs)/(true)/' \
            ./install-dependencies.sh
          sudo ./install-dependencies.sh
          sudo dnf -y install ccache lld zstd
      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-clang-nightly-${{ env.CLANG_VERSION }}-${{ matrix.build_type }}-${{ hashFiles('configure.py', 'CMakeLists.txt', 'cmake/**', '.gitmodules') }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ runner.os }}-clang-nightly-${{ env.CLANG_VERSION }}-${{ matrix.build_type }}-${{ hashFiles('configure.py', 'CMakeLists.txt', 'cmake/**', '.gitmodules') }}-
            ccache-${{ runner.os }}-clang-nightly-${{ env.CLANG_VERSION }}-${{ matrix.build_type }}-
            ccache-${{ runner.os }}-clang-nightly-${{ env.CLANG_VERSION }}-
      - name: Configure ccache
        run: |
          mkdir -p "$CCACHE_DIR"
          ccache --max-size="$CCACHE_MAXSIZE"
          ccache --zero-stats
      - name: Generate the building system
        run: |
          cmake                                         \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=clang-$CLANG_VERSION     \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache          \
            -DCMAKE_CXX_COMPILER=clang++-$CLANG_VERSION \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache        \
            -G Ninja                                    \
            -B $BUILD_DIR                               \
            -S .
      # see https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md
      - run: |
          echo "::add-matcher::.github/clang-matcher.json"
      - run: |
          cmake --build $BUILD_DIR --target scylla
      - run: |
          echo "::remove-matcher owner=clang::"
      - name: Show ccache stats
        if: ${{ always() }}
        run: |
          ccache --show-stats
