name: iwyu

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hh'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - 'cmake/**'
      - 'configure.py'
      - '.gitmodules'
      - '.github/workflows/iwyu.yaml'
      - 'flake.nix'
      - 'flake.lock'

env:
  BUILD_TYPE: RelWithDebInfo
  BUILD_DIR: build
  CLEANER_OUTPUT_PATH: build/clang-include-cleaner.log
  CLEANER_DIRS: test/unit exceptions alternator api auth cdc compaction

permissions: {}

# cancel the in-progress run upon a repush
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-include-cleaner:
    name: "Analyze #includes in source files"
    runs-on: depot-ubuntu-24.04-8
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 5G
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_NOHASHDIR: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-iwyu-${{ env.BUILD_TYPE }}-${{ hashFiles('flake.nix', 'flake.lock', 'configure.py', 'CMakeLists.txt', 'cmake/**', '.gitmodules') }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ runner.os }}-iwyu-${{ env.BUILD_TYPE }}-${{ hashFiles('flake.nix', 'flake.lock', 'configure.py', 'CMakeLists.txt', 'cmake/**', '.gitmodules') }}-
            ccache-${{ runner.os }}-iwyu-${{ env.BUILD_TYPE }}-
            ccache-${{ runner.os }}-iwyu-
      - name: Configure ccache
        run: |
          mkdir -p "$CCACHE_DIR"
          nix develop .#cpp -c ccache --max-size="$CCACHE_MAXSIZE"
          nix develop .#cpp -c ccache --zero-stats
      - name: Generate compilation database
        run: |
          nix develop .#cpp -c cmake                    \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE              \
            -DCMAKE_C_COMPILER=clang                    \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache          \
            -DScylla_SEASTAR_UNUSED_RESULT_ERROR=OFF    \
            -DCMAKE_CXX_COMPILER=clang++                \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache        \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON          \
            -G Ninja                                    \
            -B $BUILD_DIR                               \
            -S .
      - name: Build headers
        run: |
          nix develop .#cpp -c bash -c '
            swagger_targets=""
            for f in api/api-doc/*.json; do
              if test "${f#*.}" = json; then
                name=$(basename "$f" .json)
                if test $name != swagger20_header; then
                  swagger_targets+=" scylla_swagger_gen_$name"
                fi
              fi
            done
            cmake                                       \
              --build build                             \
              --target seastar_http_request_parser      \
              --target idl-sources                      \
              --target $swagger_targets
          '
      - run: |
          echo "::add-matcher::.github/clang-include-cleaner.json"
      - name: clang-include-cleaner
        run: |
          nix develop .#cpp -c bash -c '
            for d in $CLEANER_DIRS; do
              find "$d" \( -name "*.cc" -o -name "*.hh" \) \
                -exec echo {} \;                          \
                -exec clang-include-cleaner               \
                  --ignore-headers=seastarx.hh            \
                  --print=changes                         \
                  -p $BUILD_DIR                           \
                  {} \; | tee --append $CLEANER_OUTPUT_PATH
            done
          '
      - run: |
          echo "::remove-matcher owner=clang-include-cleaner::"
      - uses: actions/upload-artifact@v4
        with:
          name: Logs (clang-include-cleaner)
          path: "./${{ env.CLEANER_OUTPUT_PATH }}"
      - name: Show ccache stats
        if: ${{ always() }}
        run: |
          nix develop .#cpp -c ccache --show-stats
