name: Check Reproducible Build

on:
  schedule:
    # 5AM every friday
    - cron: '0 5 * * FRI'
  workflow_dispatch:

permissions: {}

env:
  BUILD_MODE: release
jobs:
  build-a:
    uses: ./.github/workflows/build-kuebikodb.yaml
    with:
      build_mode: release
      enable_ccache: false
  build-b:
    uses: ./.github/workflows/build-kuebikodb.yaml
    with:
      build_mode: release
      enable_ccache: false
  compare-checksum:
    runs-on: depot-ubuntu-24.04
    needs:
      - build-a
      - build-b
    steps:
      - env:
          CHECKSUM_A: ${{needs.build-a.outputs.md5sum}}
          CHECKSUM_B: ${{needs.build-b.outputs.md5sum}}
        run: |
          if [ $CHECKSUM_A != $CHECKSUM_B ]; then                             \
            echo "::error::mismatched checksums: $CHECKSUM_A != $CHECKSUM_B"; \
            exit 1;                                                           \
          fi
