name: Build with the latest Seastar

on:
  schedule:
    # 5AM everyday
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DIR: build

jobs:
  build-with-the-latest-seastar:
    runs-on: depot-ubuntu-24.04-8
    # be consistent with tools/toolchain/image
    container: scylladb/scylla-toolchain:fedora-40-20240621
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 2G
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_NOHASHDIR: true
    strategy:
      matrix:
        build_type:
          - Debug
          - RelWithDebInfo
          - Dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          rm -rf seastar
      - uses: actions/checkout@v4
        with:
          repository: scylladb/seastar
          submodules: true
          path: seastar
      - name: Install ccache
        run: |
          sudo dnf -y install ccache zstd
      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-latest-seastar-${{ matrix.build_type }}-${{ hashFiles('tools/toolchain/image', 'configure.py', 'CMakeLists.txt', 'cmake/**', '.gitmodules') }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ runner.os }}-latest-seastar-${{ matrix.build_type }}-${{ hashFiles('tools/toolchain/image', 'configure.py', 'CMakeLists.txt', 'cmake/**', '.gitmodules') }}-
            ccache-${{ runner.os }}-latest-seastar-${{ matrix.build_type }}-
            ccache-${{ runner.os }}-latest-seastar-
      - name: Configure ccache
        run: |
          mkdir -p "$CCACHE_DIR"
          ccache --max-size="$CCACHE_MAXSIZE"
          ccache --zero-stats
      - name: Generate the building system
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          cmake                                         \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=clang                    \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache          \
            -DCMAKE_CXX_COMPILER=clang++                \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache        \
            -G Ninja                                    \
            -B $BUILD_DIR                               \
            -S .
      - run: |
          cmake --build $BUILD_DIR --target scylla
      - name: Show ccache stats
        if: ${{ always() }}
        run: |
          ccache --show-stats
